### ISSUE TITLE
Element.clientHeight returns wrong value

### ISSUE THREAD

**Issue by adi-works** [christinecha/web-sparkle#2]
I can't figure out why you used `Element.clientHeight` to set the height property of each child. If my element has `100vh` it returns an equal amount in pixels, which amounts to the total height including the address bar, hence not fixing the issue at all. Did you get different results? I'm tinkering with it on Chrome `67.0.3396.87 `.

Maybe I'm missing something. I changed `Element.clientHeight` to `window.innerHeight`, and it fixes it. However, now the implementation isn't enough. We need to use `window.innerHeight` to convert `vh` to `px`.

This other project does it: https://stanko.github.io/mobile-chrome-vh-units-fix/

Strangely though, that one isn't even published to npm.

https://github.com/christinecha/web-sparkle/blob/master/packages/vh-for-mobile/index.js#L27

**Comment by christinecha** [comment]
Hey @adi518!

The reason why I changed it to clientHeight is that then, you can just set the value in CSS. So if you want it full VH, you'd set the CSS property to `height: 100vh;` - but maybe other times you'd want the element to only be 50% of the viewport height, etc.

This way it's more flexible.
